#!/usr/bin/env python3
"""
Build treatment-related QA JSON files from textrecord_*.xlsx.

Expected dataset layout:
  dataset_root/
    group1..groupN/
      PATIENT_NAME/
        textrecord_*.xlsx

This script reads Treatment* sheets (e.g., Treatment1, Treatment2, ...),
then generates 8 hierarchical treatment VQA pairs for clinical decision-making.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

from openai import OpenAI
from openpyxl import load_workbook


EVIDENCE_TYPES = {
    "Explicitly stated",
    "Inferred from plan",
    "Generated by model",
    "Requires further evaluation",
}

VQA_LEVELS: List[Dict[str, Any]] = [
    {
        "level": 1,
        "task_type": "treatment_level_1_plan_generation",
        "title": "Treatment Plan Generation",
        "question": (
            "What treatment strategies are available for this patient, and how do these "
            "plans differ conceptually?"
        ),
    },
    {
        "level": 2,
        "task_type": "treatment_level_2_necessity",
        "title": "Necessity of Treatment",
        "question": "Is active treatment necessary, or is observation or conservative treatment sufficient?",
    },
    {
        "level": 3,
        "task_type": "treatment_level_3_benefits",
        "title": "Benefits of Treatment",
        "question": (
            "What functional, skeletal, occlusal, or aesthetic improvements are expected "
            "from treatment?"
        ),
    },
    {
        "level": 4,
        "task_type": "treatment_level_4_timing",
        "title": "Timing of Treatment",
        "question": "Can treatment start immediately, or is follow-up required before definitive intervention?",
    },
    {
        "level": 5,
        "task_type": "treatment_level_5_main_strategy",
        "title": "Main Treatment Strategy",
        "question": "What is the overall treatment pathway and the main components of each plan?",
    },
    {
        "level": 6,
        "task_type": "treatment_level_6_alternative_options",
        "title": "Alternative Options",
        "question": (
            "Are there alternative strategies, and how do they differ in invasiveness, "
            "comprehensiveness, and expected outcomes?"
        ),
    },
    {
        "level": 7,
        "task_type": "treatment_level_7_plan_selection_logic",
        "title": "Plan Selection Logic",
        "question": (
            "Which plan is more comprehensive or more limited, and what factors influence "
            "plan selection?"
        ),
    },
    {
        "level": 8,
        "task_type": "treatment_level_8_decision_summary",
        "title": "Decision Summary",
        "question": (
            "What is the recommended decision direction, key selection factors, and "
            "remaining information requiring further evaluation?"
        ),
    },
]


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Build treatment QA JSON from Treatment* sheets.")
    ap.add_argument(
        "--dataset-root",
        default="/data/OralGPT/OralGPT-CMF/dataset/SH9HCMFdata",
        help="Dataset root containing group*/patient directories.",
    )
    ap.add_argument(
        "--output-dir",
        default="./outputs/patient_json_treatment",
        help="Directory to save generated per-patient JSON files.",
    )
    ap.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing patient JSON files.",
    )
    ap.add_argument(
        "--max-patients",
        type=int,
        default=None,
        help="Only process first N patients for debugging.",
    )
    ap.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of worker threads for patient-level parallel processing.",
    )
    ap.add_argument(
        "--model",
        default="gpt-4o",
        help="OpenAI model used to synthesize treatment QA answers.",
    )
    ap.add_argument(
        "--api-base",
        default="http://35.164.11.19:3887/v1",
        help="OpenAI compatible API base URL.",
    )
    ap.add_argument(
        "--api-key-env",
        default="OPENAI_API_KEY",
        help="Environment variable name that stores API key.",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Do not call LLM; use deterministic fallback answers.",
    )
    return ap.parse_args()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def normalize_text(s: Any) -> str:
    if s is None:
        return ""
    text = str(s).strip()
    if not text:
        return ""
    return re.sub(r"\s+", " ", text)


def normalize_llm_answer(s: Any) -> str:
    if s is None:
        return ""
    text = str(s).strip()
    if not text:
        return ""
    # Preserve line breaks so numbered treatment plans remain readable.
    lines = [re.sub(r"\s+", " ", line).strip() for line in text.splitlines()]
    lines = [line for line in lines if line]
    return "\n".join(lines)


def discover_patients(dataset_root: Path) -> List[Dict[str, Any]]:
    if not dataset_root.exists():
        raise FileNotFoundError(f"Dataset root does not exist: {dataset_root}")

    items: List[Dict[str, Any]] = []
    for group_dir in sorted(p for p in dataset_root.iterdir() if p.is_dir() and p.name.startswith("group")):
        for patient_dir in sorted(p for p in group_dir.iterdir() if p.is_dir()):
            textrecords = sorted(patient_dir.glob("textrecord_*.xlsx"))
            items.append(
                {
                    "group": group_dir.name,
                    "patient_name": patient_dir.name,
                    "patient_dir": patient_dir,
                    "textrecord": textrecords[0] if textrecords else None,
                }
            )
    return items


def build_unique_patient_uid(group: str, patient_name: str, patient_dir: Path, used: Dict[str, int]) -> str:
    base = f"{group}__{patient_name}"
    if base not in used:
        used[base] = 1
        return base
    used[base] += 1
    short_hash = hashlib.sha1(str(patient_dir).encode("utf-8")).hexdigest()[:8]
    return f"{base}__{short_hash}"


def json_record_template(uid: str, group: str, patient_name: str, patient_dir: Path, model: str) -> Dict[str, Any]:
    now = dt.datetime.now(dt.timezone.utc).isoformat()
    return {
        "schema_version": "1.0",
        "patient_uid": uid,
        "patient_name": patient_name,
        "group": group,
        "source_path": str(patient_dir),
        "created_at_utc": now,
        "updated_at_utc": now,
        "meta": {
            "model": model,
            "pipeline": "textrecord_treatment_qa_pipeline",
        },
        "Modalities": {},
    }


def add_task_result(
    record: Dict[str, Any],
    task_type: str,
    level: int,
    question: str,
    textrecord_path: Path,
    input_sheets: List[str],
    answer: str,
    evidence_type: str,
) -> None:
    record["Modalities"][task_type] = {
        "level": level,
        "question": question,
        "status": "success",
        "input_images": [],
        "input_textrecord": str(textrecord_path),
        "input_sheets": input_sheets,
        "answer": answer,
        "evidence_type": evidence_type,
        "error": "",
        "timestamp_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
    }
    record["updated_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()


def sheet_rows(sheet: Any) -> Iterable[List[str]]:
    for row in sheet.iter_rows(values_only=True):
        values = [normalize_text(c) for c in row]
        if any(values):
            yield values


def sheet_to_pairs(sheet: Any) -> List[Tuple[str, str]]:
    pairs: List[Tuple[str, str]] = []
    for row in sheet_rows(sheet):
        non_empty = [v for v in row if v]
        if len(non_empty) < 2:
            continue
        key = non_empty[0]
        value = " | ".join(non_empty[1:]).strip(" :;,.")
        if key and value:
            pairs.append((key, value))
    return pairs


def is_treatment_sheet(sheet_name: str) -> bool:
    return bool(re.match(r"^treatment\s*\d+$", normalize_text(sheet_name), flags=re.IGNORECASE))


def collect_treatment_data(workbook: Any) -> Dict[str, List[Tuple[str, str]]]:
    result: Dict[str, List[Tuple[str, str]]] = {}
    for name in workbook.sheetnames:
        if not is_treatment_sheet(name):
            continue
        pairs = sheet_to_pairs(workbook[name])
        if pairs:
            result[name] = pairs
    return result


def treatment_data_as_json(treatment_data: Dict[str, List[Tuple[str, str]]]) -> str:
    payload: Dict[str, List[Dict[str, str]]] = {}
    for sheet_name, pairs in treatment_data.items():
        payload[sheet_name] = [{"field": k, "value": v} for k, v in pairs]
    return json.dumps(payload, ensure_ascii=False)


def treatment_data_as_text(treatment_data: Dict[str, List[Tuple[str, str]]]) -> str:
    sections: List[str] = []
    for sheet_name in sorted(treatment_data.keys()):
        lines = [f"{field}: {value}" for field, value in treatment_data[sheet_name]]
        if lines:
            sections.append(f"{sheet_name}\n" + "\n".join(lines))
    return "\n\n".join(sections)


def extract_json_payload(text: str) -> Any:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    start_candidates = [idx for idx in (cleaned.find("["), cleaned.find("{")) if idx != -1]
    if not start_candidates:
        raise ValueError("LLM response does not contain JSON.")
    start = min(start_candidates)
    end = max(cleaned.rfind("]"), cleaned.rfind("}"))
    if end < start:
        raise ValueError("LLM response contains incomplete JSON.")
    return json.loads(cleaned[start : end + 1])


def normalize_evidence_type(value: Any) -> str:
    evidence = normalize_llm_answer(value)
    return evidence if evidence in EVIDENCE_TYPES else "Requires further evaluation"


def validate_vqa_pairs(payload: Any) -> List[Dict[str, Any]]:
    if isinstance(payload, dict):
        payload = payload.get("vqa_pairs", payload.get("VQA", payload.get("items", [])))
    if not isinstance(payload, list):
        raise ValueError("LLM response must be a list of VQA pairs.")

    by_level: Dict[int, Dict[str, Any]] = {}
    for item in payload:
        if not isinstance(item, dict):
            continue
        try:
            level = int(item.get("level", item.get("Level")))
        except (TypeError, ValueError):
            continue
        by_level[level] = item

    pairs: List[Dict[str, Any]] = []
    for spec in VQA_LEVELS:
        level = spec["level"]
        item = by_level.get(level, {})
        question = normalize_llm_answer(item.get("question", item.get("Q"))) or spec["question"]
        answer = normalize_llm_answer(item.get("answer", item.get("A")))
        evidence_type = normalize_evidence_type(
            item.get("evidence_type", item.get("Evidence Type", item.get("evidenceType")))
        )
        if not answer:
            raise ValueError(f"Missing answer for VQA level {level}.")
        pairs.append(
            {
                "level": level,
                "task_type": spec["task_type"],
                "question": question,
                "answer": answer,
                "evidence_type": evidence_type,
            }
        )
    return pairs


def call_llm_vqa_pairs(
    client: OpenAI,
    model: str,
    treatment_data: Dict[str, List[Tuple[str, str]]],
) -> List[Dict[str, Any]]:
    prompt = (
        "You are an expert in orthognathic surgery, orthodontics, and dentofacial "
        "deformity treatment planning.\n\n"
        "Your task is to convert a complete patient treatment plan into a hierarchical "
        "VQA dataset for clinical decision-making modeling, while also identifying and, "
        "if necessary, generating clinically plausible treatment options.\n\n"
        "Input:\n"
        "A full treatment plan text, which may include one or more proposed treatment "
        "strategies.\n\n"
        "Your job consists of three parts:\n\n"
        "Step 1. Treatment Option Identification and Generation\n"
        "1. Identify all treatment options present in the clinical treatment content.\n"
        "2. If the available plans are incomplete or limited, generate additional clinically "
        "reasonable treatment options based on standard orthognathic principles.\n"
        "3. Clearly distinguish plans directly present in the clinical content from plans inferred "
        "or generated by you.\n\n"
        "Step 2. Structured Treatment Plan Summary\n"
        "Summarize each treatment plan in a structured and standardized format, including "
        "orthodontic components, surgical components, treatment sequence if applicable, "
        "and core treatment objective.\n\n"
        "Step 3. Hierarchical VQA Generation\n"
        "Generate exactly 8 hierarchical VQA pairs, one for each level below, following "
        "the clinical decision-making pathway:\n"
        "Level 1 Treatment Plan Generation: What treatment strategies are available for "
        "this patient? How do these plans differ conceptually?\n"
        "Level 2 Necessity of Treatment: Is active treatment necessary? Is observation "
        "or conservative treatment sufficient?\n"
        "Level 3 Benefits of Treatment: What functional, skeletal, occlusal, or aesthetic "
        "improvements are expected?\n"
        "Level 4 Timing of Treatment: Can treatment start immediately? Is follow-up "
        "required before definitive intervention?\n"
        "Level 5 Main Treatment Strategy: What is the overall treatment pathway? What are "
        "the main components of each plan?\n"
        "Level 6 Alternative Options: Are there alternative strategies? What are the "
        "differences in invasiveness, comprehensiveness, and expected outcomes?\n"
        "Level 7 Plan Selection Logic: Which plan is more comprehensive? Which plan is "
        "more limited? What factors influence plan selection?\n"
        "Level 8 Decision Summary: Recommended decision direction, key factors affecting "
        "plan selection, and information still requiring further evaluation.\n\n"
        "Rules:\n"
        "- Base answers primarily on the clinical treatment content.\n"
        "- Do NOT fabricate specific patient findings not supported by the clinical content.\n"
        "- If uncertainty exists, explicitly state: \"This requires further clinical and "
        "imaging evaluation\".\n"
        "- Generated treatment options must follow standard orthognathic clinical practice.\n"
        "- Maintain logical progression across levels.\n"
        "- Use concise, formal, and professional medical English.\n"
        "- Avoid redundancy.\n"
        "- Answers must be direct clinical answers. Do not mention the dataset, VQA task, "
        "question-answer pair construction, model behavior, source document, input text, "
        "Treatment sheet, or phrases such as \"explicitly stated in the document\". Use "
        "the evidence_type field, not the answer text, to indicate evidence source.\n"
        "- Ensure the output is suitable for large-model training data: clear, structured, "
        "and consistent.\n\n"
        "Return only valid JSON. The JSON must be an array of exactly 8 objects. Each object "
        "must contain these keys: level, question, answer, evidence_type. The evidence_type "
        "value must be one of: Explicitly stated, Inferred from plan, Generated by model, "
        "Requires further evaluation.\n\n"
        f"Clinical treatment data JSON: {treatment_data_as_json(treatment_data)}\n\n"
        f"Clinical treatment content:\n{treatment_data_as_text(treatment_data)}\n"
    )
    completion = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": "You generate faithful hierarchical clinical VQA pairs from dental treatment plans.",
            },
            {"role": "user", "content": prompt},
        ],
    )
    payload = extract_json_payload(completion.choices[0].message.content or "")
    return validate_vqa_pairs(payload)


def fallback_plan_answer(treatment_data: Dict[str, List[Tuple[str, str]]]) -> str:
    parts: List[str] = []
    sheet_names = sorted(treatment_data.keys())
    if len(sheet_names) > 1:
        parts.append("Multiple treatment strategies are available.")
    for idx, sheet_name in enumerate(sheet_names, start=1):
        items = [f"{k}: {v}" for k, v in treatment_data[sheet_name]]
        if not items:
            continue
        parts.append(f"Plan {idx}: " + "; ".join(items) + ".")
    return " ".join(parts).strip()


def fallback_vqa_pairs(treatment_data: Dict[str, List[Tuple[str, str]]]) -> List[Dict[str, Any]]:
    plan_summary = fallback_plan_answer(treatment_data)
    fallback_answers = {
        1: (
            f"The available strategies include the following treatment pathways. {plan_summary} "
            "Conceptual differences between camouflage, orthognathic correction, and aesthetic "
            "contouring cannot be fully determined from the available clinical details alone. "
            "This requires further clinical and imaging evaluation."
        ),
        2: (
            "Active treatment is suggested by the presence of a defined treatment pathway, but whether "
            "observation or conservative treatment would be sufficient requires correlation with "
            "symptoms, occlusion, skeletal findings, and patient goals."
        ),
        3: (
            "Expected benefits may include skeletal, occlusal, functional, or aesthetic improvement "
            "depending on the selected components. "
            "Specific patient-level benefits require further clinical and imaging evaluation."
        ),
        4: (
            "The available clinical details do not establish whether treatment can start immediately. "
            "Timing should depend on completion of diagnostic evaluation, treatment readiness, and any "
            "need for follow-up before definitive intervention."
        ),
        5: (
            f"The main pathway consists of the following treatment components: {plan_summary} "
            "Orthodontic, surgical, sequencing, and objective details should be confirmed against the "
            "complete clinical record."
        ),
        6: (
            "Alternative strategies may include conservative observation, orthodontic camouflage, "
            "orthodontic-orthognathic correction, or adjunctive contouring/genioplasty when clinically "
            "appropriate. These generated alternatives differ in invasiveness, comprehensiveness, and "
            "expected skeletal or aesthetic impact."
        ),
        7: (
            "A comprehensive plan generally addresses skeletal discrepancy, occlusion, function, and "
            "aesthetics, while a limited plan may focus on camouflage or contouring. Plan selection "
            "depends on deformity severity, occlusion, airway/TMJ status, patient preference, risk, "
            "and diagnostic findings."
        ),
        8: (
            "Decision direction should prioritize the most clinically comprehensive pathway while "
            "considering reasonable alternatives. Key selection factors include treatment objective, "
            "invasiveness, expected functional and aesthetic outcomes, patient preference, and missing "
            "diagnostic information. This requires further clinical and imaging evaluation."
        ),
    }
    evidence_by_level = {
        1: "Explicitly stated",
        2: "Inferred from plan",
        3: "Inferred from plan",
        4: "Requires further evaluation",
        5: "Explicitly stated",
        6: "Generated by model",
        7: "Inferred from plan",
        8: "Requires further evaluation",
    }
    return [
        {
            "level": spec["level"],
            "task_type": spec["task_type"],
            "question": spec["question"],
            "answer": fallback_answers[spec["level"]],
            "evidence_type": evidence_by_level[spec["level"]],
        }
        for spec in VQA_LEVELS
    ]


def safe_vqa_pairs(
    client: OpenAI | None,
    model: str,
    treatment_data: Dict[str, List[Tuple[str, str]]],
) -> List[Dict[str, Any]]:
    if not treatment_data:
        return []
    fallback = fallback_vqa_pairs(treatment_data)
    if client is None:
        return fallback
    try:
        return call_llm_vqa_pairs(client=client, model=model, treatment_data=treatment_data)
    except ValueError:
        return fallback


def process_one_patient(
    item: Dict[str, Any],
    uid: str,
    output_path: Path,
    overwrite: bool,
    client: OpenAI | None,
    model: str,
) -> Dict[str, Any]:
    if output_path.exists() and not overwrite:
        return {"uid": uid, "status": "exists", "skipped": True}

    record = json_record_template(
        uid=uid,
        group=item["group"],
        patient_name=item["patient_name"],
        patient_dir=item["patient_dir"],
        model=model if client else "fallback_rule_based",
    )

    textrecord_path: Optional[Path] = item["textrecord"]
    if textrecord_path is None or not textrecord_path.exists():
        output_path.write_text(json.dumps(record, ensure_ascii=False, indent=2), encoding="utf-8")
        return {"uid": uid, "status": "missing_textrecord", "skipped": False}

    wb = load_workbook(filename=str(textrecord_path), data_only=True)
    treatment_data = collect_treatment_data(wb)
    used_sheets = sorted(treatment_data.keys())

    if not treatment_data:
        output_path.write_text(json.dumps(record, ensure_ascii=False, indent=2), encoding="utf-8")
        return {"uid": uid, "status": "missing_treatment_sheets", "skipped": False}

    for pair in safe_vqa_pairs(client=client, model=model, treatment_data=treatment_data):
        add_task_result(
            record=record,
            task_type=pair["task_type"],
            level=pair["level"],
            question=pair["question"],
            textrecord_path=textrecord_path,
            input_sheets=used_sheets,
            answer=pair["answer"],
            evidence_type=pair["evidence_type"],
        )

    output_path.write_text(json.dumps(record, ensure_ascii=False, indent=2), encoding="utf-8")
    return {"uid": uid, "status": "written", "skipped": False}


def run_pipeline(args: argparse.Namespace) -> None:
    dataset_root = Path(args.dataset_root).resolve()
    output_dir = Path(args.output_dir).resolve()
    ensure_dir(output_dir)

    patients = discover_patients(dataset_root)
    if args.max_patients is not None:
        patients = patients[: args.max_patients]

    workers = max(1, args.workers)
    api_key = os.getenv(args.api_key_env, "")
    if (not args.dry_run) and (not api_key):
        raise RuntimeError(f"Missing API key. Set environment variable: {args.api_key_env}")
    client = None if args.dry_run else OpenAI(api_key=api_key, base_url=args.api_base)

    used_uid: Dict[str, int] = {}
    jobs: List[Tuple[Dict[str, Any], str, Path]] = []
    for item in patients:
        uid = build_unique_patient_uid(item["group"], item["patient_name"], item["patient_dir"], used_uid)
        output_path = output_dir / f"{uid}.json"
        jobs.append((item, uid, output_path))

    total = len(jobs)
    print(
        f"[INFO] Found {total} patients under {dataset_root}; "
        f"workers={workers}, dry_run={args.dry_run}"
    )

    try:
        from tqdm import tqdm  # type: ignore

        bar: Any = tqdm(total=total, desc="patients", unit="patient")
        use_tqdm = True
    except Exception:
        bar = None
        use_tqdm = False

    completed = 0
    with ThreadPoolExecutor(max_workers=workers) as executor:
        future_map = {
            executor.submit(
                process_one_patient,
                item,
                uid,
                output_path,
                args.overwrite,
                client,
                args.model,
            ): (uid, output_path)
            for item, uid, output_path in jobs
        }
        for future in as_completed(future_map):
            uid, output_path = future_map[future]
            completed += 1
            try:
                res = future.result()
                msg = f"[{completed}/{total}] {uid}: {res['status']} -> {output_path}"
            except Exception as e:
                msg = f"[{completed}/{total}] {uid}: ERROR - {e}"

            if use_tqdm:
                bar.update(1)
                bar.write(msg)
            else:
                print(msg)

    if use_tqdm:
        bar.close()
    print("[INFO] Pipeline completed.")


if __name__ == "__main__":
    run_pipeline(parse_args())
